# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('bname', models.CharField(max_length=70)),
                ('color', models.CharField(max_length=70)),
                ('bloc', models.CharField(max_length=70)),
                ('alcholic', models.CharField(max_length=80)),
            ],
        ),
    ]
